# Copyright 2025 Robert Lindley
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# without warranties or conditions of any kind, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

author: Robert Lindley
name: Commit and Push Changes
description: |
  This action automates committing and pushing code changes to a GitHub repository.
  It ensures updates are regularly applied without manual intervention while following security best practices.

branding:
  color: 'blue'
  icon: 'git-commit'

inputs:
  github-token:
    default: ${{ github.token }}
    description:
      GitHub token used for authentication (must have minimal required scopes)
    required: false
  github-hostname:
    default: 'github.com'
    description: GitHub hostname (useful for enterprise installations)
    required: false
  author-name:
    default: 'GitHub Actions'
    description: Name of the commit author
    required: false
  author-email:
    default: 'github-actions@noreply.github.com'
    description: Email of the commit author
    required: false
  sign-commit:
    default: 'false'
    description: Whether to sign commits using GPG (true/false)
    required: false
  commit-message:
    default: 'Automated commit by GitHub Actions'
    description: Commit message for the changes
    required: false
  remote-ref:
    default: 'origin'
    description: Remote repository reference
    required: false
  branch-target:
    default: 'main'
    description: Name of the branch to push the code into
    required: false
  create-branch:
    default: 'false'
    description: Create branch if it does not exist
    required: false
  directory-path:
    default: '.'
    description: Path to the directory containing files to commit and push
    required: false
  force-push:
    default: 'false'
    description: Whether to force push (true/false)
    required: false

outputs:
  commit-hash:
    description: The hash of the latest commit

runs:
  using: 'node20'
  main: 'dist/index.mjs'
